# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: http://www.liujiebin.com
date_format: "ordinal"
title: Anohana | 东流的博客
subtitle: "纵使没有阳光,仍旧持续歌唱"
description: "东流(anohana)，PHP工程师，从事web相关的开发工作 目前贡献于B站"
keywords: 东流, php, bilibili
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: zoooozz
organization: bilibili, Inc.
organization_url: https://www.bilibili.com
location: Shanghai, China
email: zoooozz@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: Home

  -
    href: /categories/
    label: categories

  -
    href: /wiki/
    label: wiki

  -
    href:  http://space.bilibili.com/8746433/#!/
    label: space

  -
    href: /about/
    label: about

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: zoooozz/zoooozz.github.io

# ---------------- #
#      Socials     #
# ---------------- #
github_username: zoooozz
# douban_username: 
# facebook_username: 
# weibo_username: 
# zhihu_username: 
# twitter_username: 

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
# comments_provider: disqus
# duoshuo_username: zoooozz
# disqus_username: zoooozz
# 在使用 disqus 的时候可点击显示多说评论框
# lazy_load_duoshuo: true


# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: []
